#!/usr/bin/env bash
# Script that displays specific information about subdomains

domain_info(){
    dig "$2.$1" | grep -A1 "ANSWER SECTION:" | grep "$2" | awk -v sdomain="$2" '{print "The subdomain " sdomain " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    domain_info "$1" "$2"
fi

# awk -v-> Assigns var value
