#!/usr/bin/env bash
# Transfer a file from our client to a server

error="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -le 3 ];
then
    echo error
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
