#!/usr/bin/env bash
#Run Nginx as nginx user, but short this time.
pkill apache2
chown nginx:nginx /etc/nginx/
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
